### ISSUE TITLE
Add the required homework directory

### ISSUE THREAD

**Issue by vanhanenjjv** [MikkoWrightson/5G00EV06-3001-wrightson-mikko#1]
According to the specs, you are required to have a homework directory, bro 🙈

**Comment by MikkoWrightson** [comment]
According to the specs, you are required to GET A JOB



Also git doesn't include empty directories.

**Comment by vanhanenjjv** [comment]
> According to the specs, you are required to GET A JOB
> 
> Also git doesn't include empty directories.

That is why you commit .gitkeep files in directories that are empty but you want to include in version control.
